services:
  - type: web
    name: myprofile-app
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet MyProfile.dll
    buildFilter:
      paths:
        - "**/*"
    rootDir: .
